using RelhaxModpack.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RelhaxModpack.Database
{
    /// <summary>
    /// A structure that is used to track the relative path of a user file (like session stats),
    /// and the root path between the installer and WoT directory
    /// </summary>
    public struct UserDataFile
    {
        /// <summary>
        /// The WoT root directory where the UserDataFile is from
        /// </summary>
        public string WoTRoot;

        /// <summary>
        /// The directory path to the Relhax installer temporary folder for holding user files during an installation
        /// </summary>
        public string TempSaveRoot;

        /// <summary>
        /// The relative path of the user file
        /// </summary>
        public string FilePath;
    }
    /// <summary>
    /// An object that represents cache files generated by mods that should be backed up and restored as to not loose cache data (like session stats or auto equip data)
    /// </summary>
    public class UserFile : XmlDatabaseComponent, IXmlSerializable
    {
        #region Xml serialization V1
        /// <summary>
        /// Defines a list of properties in the class to be serialized into xml attributes
        /// </summary>
        /// <returns>A list of string property names</returns>
        /// <remarks>Xml attributes will always be written, xml elements are optional</remarks>
        public string[] PropertiesForSerializationAttributes()
        {
            return new string[] { nameof(Pattern) };
        }

        /// <summary>
        /// Defines a list of properties in the class to be serialized into xml elements
        /// </summary>
        /// <returns>A list of string property names</returns>
        /// <remarks>Xml attributes will always be written, xml elements are optional</remarks>
        public string[] PropertiesForSerializationElements()
        {
            return new string[] { };
        }
        #endregion

        #region Xml serialization V2
        protected override List<XmlDatabaseProperty> GetXmlDatabasePropertiesV1Dot0()
        {
            List<XmlDatabaseProperty> xmlDatabaseProperties = new List<XmlDatabaseProperty>()
            {
                //list attributes
                new XmlDatabaseProperty() { XmlName = nameof(Pattern), XmlEntryType = Utilities.Enums.XmlEntryType.XmlAttribute, PropertyName = nameof(Pattern) }
            };
            return xmlDatabaseProperties;
        }
        #endregion

        /// <summary>
        /// The path or pattern to a file or files to backup to a temporary directory
        /// </summary>
        public string Pattern { get; set; } = string.Empty;

        /// <summary>
        /// The list of actual files saved to the temporary backup directory. Contains the full path and file name
        /// </summary>
        public List<UserDataFile> FilesSaved { get; } = new List<UserDataFile>();

        /// <summary>
        /// The string representation of the UserFile object
        /// </summary>
        /// <returns>The string pattern</returns>
        public override string ToString()
        {
            return Pattern;
        }

        /// <summary>
        /// Create a copy of the UserFile object
        /// </summary>
        /// <param name="userFileToCopy">The object to copy</param>
        /// <returns>A new UserFile object with the same values</returns>
        public static UserFile Copy(UserFile userFileToCopy)
        {
            UserFile file =  new UserFile()
            {
                Pattern = userFileToCopy.Pattern,
            };

            return file;
        }

        /// <summary>
        /// Create a deep copy of the UserFile object
        /// </summary>
        /// <param name="userFileToCopy">The object to copy</param>
        /// <returns>A new UserFile object with the same values and new list elements with the same values</returns>
        public static UserFile DeepCopy(UserFile userFileToCopy)
        {
            UserFile file = new UserFile()
            {
                Pattern = userFileToCopy.Pattern,
            };

            file.FilesSaved.AddRange(userFileToCopy.FilesSaved);

            return file;
        }
    }
}
